[package]
name = "rpi_fft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.10"
rustfft = "6.1.0"
heapless = "0.7"
egui = "0.21.0"
eframe = "0.21.3"
